"""add owner_id to leaderboard

Revision ID: c80cbbd407e0
Revises: 
Create Date: 2025-07-26 21:57:33.818166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c80cbbd407e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaderboard', sa.Column('owner_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('leaderboard_username_key'), 'leaderboard', type_='unique')
    op.create_unique_constraint(None, 'leaderboard', ['owner_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leaderboard', type_='unique')
    op.create_unique_constraint(op.f('leaderboard_username_key'), 'leaderboard', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('leaderboard', 'owner_id')
    # ### end Alembic commands ###
